name: Check Aws Access 

on:
  push:
    branches:
        -main

jobs:
   check-access:
    runs-on: ubuntu-latest

steps:
-name: checkout code
 uses: actions/checkout@v3

 -name: configure AWS credentials
 uses: aws-actions/configure-aws-credentials@v2
 with: 
   aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
   aws-secret-access-key: ${{secrets.AWS_ SECRET_ACCESS_KEY}}
   aws-region: ${{secrets.AWS_REGION}}

   -name: verify AWS credentials
   run: aws sts get-caller-identity
    
